### ISSUE TITLE
source--source alignment !

### ISSUE THREAD

**Issue by BilalKoteich** [dice-group/LIMES#170]
Hi.

I'm using Limes to align data sets, but I noticed 2 things:

- the alignments are not only source <-> target, in some cases I had alignments source <-> source !

- when Limes finds a matching between two instances, maybe it stops and does not continue to seek if there is a second matching for exemple.

are they bugs or not?

Thanks.

**Comment by Kleanthi** [comment]
Can you please specify which source and target KBs are you using? 
What do you mean by second matching?

**Comment by BilalKoteich** [comment]
I am using 2 local datasets. Source : TAXREF-LD, Target: Geospecies 

- I had a lot of results like this:
< http://taxref.mnhn.fr/lod/name/93143 > < http://www.w3.org/2004/02/skos/core#closeMatch > < http://taxref.mnhn.fr/lod/name/93144 > .

- for example if we have an instance X with a label "foo" in the source dataset, and in the target dataset we have an instance Y with a label "foo" and an instance Z with a label "foo". So Limes does an alignment between X - Y and X - Z or only X - Y?

**Comment by Kleanthi** [comment]
Regarding the first issue, please delete any local cache folder and any results files LIMES has produced using these KBs, then simply re-run your experiment. Are you sure that some source instances are not included in your target KB as well? Also can you please give me the LS you are using?

LIMES is able to identify n-to-m links between resources, not 1-to-m. So maybe there is no link between X and Z because they do not satisfy the conditions that are described by your LS.

**Comment by BilalKoteich** [comment]
I deleted the cache and tried again and got the same result. and I'm sure the target dataset does not contain any instance of the source dataset.

[LS.txt](https://github.com/dice-group/LIMES/files/2090036/LS.txt)

**Comment by Kleanthi** [comment]
Regarding exact match, we had a similar issue but we fixed it. Which release version are you using?

**Comment by BilalKoteich** [comment]
Ok. Thanks.

**Comment by kvndrsslr** [comment]
Hello, I have had a look at the source of exact match in 1.3.0 and its tests in particular, they appear to be fine (i couldn't reproduce your problem).
There was a similar problem prior to 1.2.4 tho, so maybe you don't have the right version.
Please try the following steps and if they still do not help you, I would need a copy of your datasets (or a minimal example producing the error) in order to reproduce and debug the issue:
```
git clone https://github.com/dice-group/LIMES.git
cd LIMES
git checkout 1.3.0
mvn clean package shade:shade -Dcheckstyle.skip=true -Dmaven.test.skip=true
java -jar limes-core/target/limes-core-1.3.0.jar ${YOUR_CONFIG_FILE}
```
Obviously, replace `${YOUR_CONFIG_FILE}` with the actual path to your configuration.

**Comment by BilalKoteich** [comment]
Thank you for your reply.

I tried the steps mentioned above (exectly the same steps), and i had the same results.
The two dataset (source and target) that I'm using are very big, so I'll find a way to generate the minimal example producing the error and uplaod it here.

Note: i had the same problem with 3 different dataset.

**Comment by kvndrsslr** [comment]
Thanks for reporting, this was indeed a subtle bug that only surfaced under conditions we had not covered in our tests before!
I am preparing a patch release 1.3.1 now, once it's done this issue will be closed.

**Comment by BilalKoteich** [comment]
ok.

Thank you.

**Comment by kvndrsslr** [comment]
[LIMES 1.3.1](https://github.com/dice-group/LIMES/releases/tag/1.3.1) is now available!
